### ISSUE TITLE
devto Found 0 remote article : Error: Cannot find published article on dev.to

### ISSUE THREAD

**Issue by ksingh7** [sinedied/devto-cli#24]
@sinedied first of all this look like a very interesting tool (although it has not worked for me yet and hence reaching out to you for some help)

I tried to use both your Github Action as well as the standalone CLI utility, both did not work.

So I am trying to publish `posts/blog-m1.md` which is a fresh new blog on Dev.to using your CLI. It seems like the CLI is first trying to retrieve articles from dev.to (which i am not sure why it does that) and later trying to push and fails with error `Found 0 remote articles`

The details logs are here, i would appreciate your help @sinedied if you can help me get around this error
```
$ dev push posts/blog-1.md --token xxxxxx --verbose
  push files: [ 'posts/blog-1.md' ] +0ms
  push options: {
  push   devtoKey: 'xxx',
  push   repo: undefined,
  push   branch: undefined,
  push   dryRun: false,
  push   reconcile: false,
  push   checkImages: true
  push } +3ms
  repo Repository found in git origin: ksingh7/rhd-blogs +0ms
  push repository: { user: 'ksingh7', name: 'rhd-blogs' } +48ms
  push branch: main +18ms
Found 1 article(s)
  push Retrieving articles from dev.to… +17ms
  devto Requesting articles (page 1) +0ms
  devto Found 0 remote article(s) +540ms
  push Retrieved 0 article(s) +540ms
  push Pushing articles to dev.to… +0ms
Error: Cannot find published article on dev.to: Mastering Machine Learning
Push failed
```

**Comment by ksingh7** [comment]
FYI here is blog-1.md file

```
---
title: Mastering Machine Learning
published: false
description: A simple test article
tags: 'productivity, beginners, test'
cover_image: ./assets/cat.jpeg
canonical_url: null
id: 853728
---

Some random text with a [link](https://code.visualstudio.com).

## Serious title

Add some text here and there!

![and some pictures too](./assets/cat.jpeg)

## Some Code Snippet

```python

def myFunction()
  return true
  
```
Done!

```

**Comment by ksingh7** [comment]
![image](https://user-images.githubusercontent.com/9701902/152792124-c8e76269-780a-4bdd-9af6-743946bec646.png)

**Comment by ksingh7** [comment]
managed to get it working, thanks for this great tool

@sinedied again for this great tool.

**Comment by sinedied** [comment]
Good to know that you solved it 🙂
