### ISSUE TITLE
initGitRepository() harcoded to create main branch even instead of branch injected with dev init --branch

### ISSUE THREAD

**Issue by jikuja** [sinedied/devto-cli#32]
https://github.com/sinedied/devto-cli/commit/867d905c34d5c3cc99451824a06012007c6992b5 added feature to create main branch instead of master when initing directory. initGitRepository() method probably should create a branch requested by user with --branch flag or with interactive prompt.

**Comment by sinedied** [comment]
Git repository initialization is just a convenience feature, and `main` is the default branch, but since the `--branch` option is documented as a general option it would be better to make use of it, you're right 🙂
