### ISSUE TITLE
devto init creates broken .github/workflows/publish.yml file

### ISSUE THREAD

**Issue by jikuja** [sinedied/devto-cli#5]
Publish.yml created by init command creates contains values not used by the action:

`Unexpected input(s) 'repository', 'files_glob', valid inputs are ['devto_key', 'github_token', 'files', 'conventional_commits']`

Template repository has correct format: https://github.com/sinedied/publish-devto-template/blob/master/.github/workflows/publish.yml

**Comment by sinedied** [comment]
Thanks for the report. This tool is heavily under WIP, all of these should be fixed for the initial release

**Comment by sinedied** [comment]
This should be fixed in `1.1.0` release 😉
